import type { NextPage } from "next";
import Head from "next/head";

import { MainContainer } from "@/components/layout/main-container";
import { Button } from "@/components/ui/button";

import { api } from "@/lib/utils/api";

const Dashboard: NextPage = () => {
  const postQuery = api.post.all.useQuery();

  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Dashboard - CraftyFoodz</title>
      </Head>
      <MainContainer>
        <h1>Login</h1>
        <div className="px-4 py-2">
          <Button>Hello</Button>
        </div>
      </MainContainer>
    </>
  );
};

export default Dashboard;
