import type { NextPage } from "next";
import Head from "next/head";

import { MainContainer } from "@/components/layout/main-container";
import { SiteHeader } from "@/components/site-header";
import { Button } from "@/components/ui/button";

import { UI_CONFIG } from "@/lib/config";

const Dashboard: NextPage = () => {
  return (
    <>
      <Head>
        <title>Dashboard - {UI_CONFIG.company_name}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <MainContainer>
        <SiteHeader />
        <h1>Login</h1>
        <div className="px-4 py-2">
          <Button>Hello</Button>
        </div>
      </MainContainer>
    </>
  );
};

export default Dashboard;
