import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

import { ContentToContainer } from "@/components/layout/content-to-container";
import { MainContainer } from "@/components/layout/main-container";
import { SideNavigation } from "@/components/side-navigation";
import { SiteHeader } from "@/components/site-header";

import { UI_CONFIG } from "@/lib/config";

const CustomFeaturesPage: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>{`Custom | Features - ${UI_CONFIG.company_name}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <MainContainer>
        <SiteHeader pathname={router.pathname} />
        <ContentToContainer>
          <div className="grid grid-cols-12">
            <div className="col-span-12 py-4 md:col-span-2 md:px-2">
              <SideNavigation title="Features">
                <SideNavigation.Item
                  href="/features/global"
                  active={router.pathname.toLowerCase() === "/features/global"}
                >
                  Global
                </SideNavigation.Item>
                <SideNavigation.Item
                  href="/features/custom"
                  active={router.pathname.toLowerCase() === "/features/custom"}
                >
                  Custom
                </SideNavigation.Item>
              </SideNavigation>
            </div>
            <div className="col-span-12 pb-4 pt-6 md:col-span-10 md:pt-12">
              Custom
            </div>
          </div>
        </ContentToContainer>
      </MainContainer>
    </>
  );
};

export default CustomFeaturesPage;
