import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { AlertCircle } from "lucide-react";

import { ContentToContainer } from "@/components/layout/content-to-container";
import { MainContainer } from "@/components/layout/main-container";
import { SideNavigation } from "@/components/side-navigation";
import { SiteHeader } from "@/components/site-header";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

import { UI_CONFIG } from "@/lib/config";

const CustomFeaturesPage: NextPage = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>{`Restaurant | Features - ${UI_CONFIG.company_name}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <MainContainer>
        <SiteHeader pathname={router.pathname} />
        <ContentToContainer>
          <div className="grid grid-cols-12">
            <div className="col-span-12 py-4 md:col-span-3 md:px-2">
              <SideNavigation title="Features">
                <SideNavigation.Item href="/features/global">
                  Global
                </SideNavigation.Item>
                <SideNavigation.Item
                  href="/features/restaurant-specific"
                  active
                >
                  Restaurant specific
                </SideNavigation.Item>
              </SideNavigation>
            </div>
            <div className="col-span-12 pb-4 pt-6 md:col-span-9 md:pt-4">
              <h2 className="mb-4 text-lg font-medium leading-3 transition sm:flex">
                Restaurant specific
              </h2>
              <p className="mb-6 text-sm">
                This gives you more granular control of the features applied to
                restaurants on the {UI_CONFIG.company_name} platform.
              </p>
              <Alert variant="warning">
                <AlertCircle className="h-4 w-4" />
                <AlertTitle>IMPORTANT</AlertTitle>
                <AlertDescription>
                  These settings will override the{" "}
                  <Link
                    href="/features/global?tab=restaurants"
                    className="underline underline-offset-2"
                  >
                    global feature configurations
                  </Link>{" "}
                  for the selected restaurant.
                </AlertDescription>
              </Alert>
              <section></section>
            </div>
          </div>
        </ContentToContainer>
      </MainContainer>
    </>
  );
};

export default CustomFeaturesPage;
